### ISSUE TITLE
Problem statement review

### ISSUE THREAD

**Issue by tingyuw** [tingyuw/cas741#1]
Hello Dr. Smith!
Please take a look at my problem statement and thanks in advance for the feedback!

https://github.com/tingyuw/cas741/blob/master/documents/problemStatement/ProblemStatement.pdf
https://github.com/tingyuw/cas741/blob/master/documents/problemStatement/ProblemStatement.tex

**Comment by smiths** [comment]
@tingyuw, your problem statement is fine, but there are some writing and github related problems that we should sort out now (so that they aren't an issue in the future).  My comments are as follows:

- Please review the writing checklist (in the docs folder of the blank project template).  Specifically, please do the following:
  - include the `Comments.tex` file
  - match the blank project template folder structure, folder names and file names
  - hard-wrap at 80 characters
  - include the `.gitignore` file from the blank project template
- Please review the problem statement checklist.  Specifically, please do the following:
  - modify the problem statement so that it is abstract.  There is no reason to constrain your software to only work on Windows
  - what are the inputs to your software?
  - since you are doing  your problem in Drasil, you should explicitly mention this in the problem statement
  - in the future, including the commit hash for your problem statement would be helpful
- You don't need periods after the sub-section titles

Once you have addressed the above points, we'll close this issue, and I'll approve your problem statement.

**Comment by tingyuw** [comment]
@smiths 
I have addressed the above points.  Please review and let me know if there are other problems. 
Thank you!

- https://github.com/tingyuw/cas741/blob/master/docs/ProblemStatement/ProblemStatement.pdf
- https://github.com/tingyuw/cas741/blob/master/docs/ProblemStatement/ProblemStatement.tex

**Comment by smiths** [comment]
The changes look good.  Thank you @tingyuw.  Your problem statement is approved.  :smile:
