### ISSUE TITLE
Drasil - two outputs in a model

### ISSUE THREAD

**Issue by tingyuw** [tingyuw/cas741#25]
Hello @smiths 
I have two outputs in some of my IMs, but it seems like we could only have one output in each of the Drasil IM, right?
I'm not sure did I miss something or just I don't know how to do it. I separated the outputs into different IM for now. 
Is it a better approach to have only one output for each IM? 

![image](https://user-images.githubusercontent.com/47548045/100060032-01c9ac00-2dfa-11eb-8e11-c7db006e94eb.png)

**Comment by smiths** [comment]
@tingyuw from a mathematical point of view, there is nothing wrong with multiple outputs, but I believe that Drasil doesn't like more than one output because of code generation.  If you can write each IM for one output that would be better.  It might be possible to change the type of the output to a tuple, which would let you combine multiple outputs into one output.  (Each of the multiple outputs would become a field of the tuple that forms the single output.)  I'm not sure if Drasil supports this approach though.  The conservative option of one output per IM will definitely work, and I think it makes sense for your problem.

**Comment by tingyuw** [comment]
@smiths I see. It does make sense that to have only one output for each IM for technical reason. Just wondering that maybe in some cases we would have two outputs in a model.

**Comment by smiths** [comment]
@tingyuw, you can think about the way that Drasil currently handles multiple outputs as analogous to how programming languages handle multiple outputs.  Not all programming languages allow this.  In the C programming language a function can return only one variable.  In cases where the programmer wants more outputs, they define the type of that variable to be a structure.  In the long run, we will have a closer look at how Drasil handles outputs, but we won't be changing the implementation in the short term.

**Comment by tingyuw** [comment]
@smiths I got it. I didn't think about the programming aspect. Thank you!
