### ISSUE TITLE
SRS review

### ISSUE THREAD

**Issue by tingyuw** [tingyuw/cas741#3]
Hello all, 
My SRS is ready to review. 
Please take a look at it and thanks in advance for the feedback!
@machadotiagom @yanxuanm 

- https://github.com/tingyuw/cas741/blob/master/docs/SRS/SRS.pdf
- https://github.com/tingyuw/cas741/blob/master/docs/SRS/SRS.tex

**Comment by smiths** [comment]
Thank you @tingyuw.  I'll get to the review as soon as I can.

**Comment by machadotiagom** [comment]
Hi @tingyuw 

I have read your SRS document and here go my comments. Hope that helps you on the CAS 741 project.

**Section 2.3 Characteristics of Intended Reader**
Could you be more specific on this? I mean, what does it mean to have a knowledge level 3 in mechanical engineering? This understanding might vary from university to university or from country to country.

**Section 3.2 User Characteristics**
Are the users of the Truss software only the same target audience pointed out as the intended reader of this SRS document? Usually, that is not what happens in a real-world context.

**Section 4.2.1**
What is the original problem that you are simplifying? A bit of context is missed here I guess. I meant, it is not clear to what extent the problem is complex (of course I can guess that calculate the truss for building a bridge is very complicated), but as we are looking at how to specify properly the problems that we intend to solve through an SRS document, I believe that we should try to state the problem better. It is just my impression, I am trying to make questions that can help you to make a good SRS as possible.

**Theoretical models section**
Don't you have to describe that the equations return the summation of forces in a given direction and that at a certain point all of them must be equal to zero for the system to be stable? Looks like you just described the Fix and Fiy forces but doesn't explain the overall meaning of the equation. Also, you did not mention the unit of measurement.

**Data definition section**
_DD1:_ at the notes cell, looks like there is a coherence issue in the sentence. I am not a native English speaker, so you can skip it if you feel that it is ok. Anyway, something is missing when I read it.

**Instance models section**
Could you make a reference to the figure 2 at the description of each IM? since you point out forces in truss 1, 2, 3, and 4, I guess you are speaking of figure 2, aren't you?

**Functional requirements section**
R0 and R1 don't seem a requirement for me. Looks like more a design (how to) instead of "what to do" as an SRS document would be expected to be.

**Nonfunctional requirements section**
I do not have a background in SW/CS, so I am not sure if nonfunctional requirements are presented the way you presented. I meant, for instance, when you say that correct is achieved by outputs having the properties described in Table 4.2.7 for instance, what does that mean? that your code behaves like the way it was supposed to behave as described in the functional requirement? I suggest you double-check with Prof Spencer if it is valid to present it the way you did.

Thanks
Tiago.

**Comment by smiths** [comment]
@tingyuw, you may want to split the feedback from @machadotiagom into separate issues for ease of tracking.  Alternatively, you can use commit messages with specific commit hashes to identify the commit that closes aspects of the issue.  (@machadotiagom, if possible, when you give feedback in the future, can you please split it into separate issues.)

**Comment by smiths** [comment]
@tingyuw, I have provided feedback on your SRS through issue #15 and in 83ae6dc.  Please create any issues out of my comments that you find useful for completing your revisions.
