### ISSUE TITLE
TM and GD

### ISSUE THREAD

**Issue by yanxuanm** [tingyuw/cas741#5]
Hi Ting-Yu, 

I think the TM that you have listed looks like GD for me. 

TM should be something like Newton's law, Method of section and method of joints are approaches for analyzing truss forces.  These are method developed by engineers. TM should be something that physically describable, or constitutive equations like general stain & stress, Young's modulus.

Hope this will make sense. 
Xuanming

**Comment by smiths** [comment]
@tingyuw, I have not yet reached the point of reviewing your document, but @yanxuanm has some excellent feedback here.  The TM for the truss problem is static equilibrium (the sum of the forces in each direction is zero, and the sum of the moments is zero).  This is the same TM as for the beam example that I pointed you toward.  The same TM is also in the game physics example, although it is a bit more complicated because in that case there is acceleration (linear and angular).

**Comment by tingyuw** [comment]
@smiths 
I have addressed the TM to the sum of the forces and the sum of the  moments with a09dfbdd86061721214a971d3628c015a9d7305f.
Also, I was wondering, as you mentioned in the feedback that I moved my DDs to IMs because they are part of the output. In that case, is it right to not having GD and DD?

**Comment by smiths** [comment]
@tingyuw it is fine to not have GDs or DDs.  It is unusual, but if they aren't needed, then they aren't needed.  :smile:
